name: pipeline
on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: goanpeca/setup-miniconda@v1.1.4
        with:
          miniconda-version: '4.7.12'
      - name: setup
        run: |
          ./env-init.sh
          echo "{}" > ~/.databricks-connect
          eval "$(conda shell.bash hook)"
          source $HOME/.poetry/env
          conda activate $PWD/.venv
      - name: pylint
        run: |
          eval "$(conda shell.bash hook)"
          conda activate $PWD/.venv
          ./pylint.sh
      - name: crlf
        run: |
          eval "$(conda shell.bash hook)"
          conda activate $PWD/.venv
          ./check-crlf.sh
      - name: tests
        run: |
          eval "$(conda shell.bash hook)"
          conda activate $PWD/.venv
          ./run_tests.sh
